/**
 * 予約タスクファクトリー
 */
import { IAttributes as IReserveActionAttributes } from '../action/reserve';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    actionAttributes: IReserveActionAttributes[];
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.Reserve;
    data: IData;
}
export type ITask = IExtendId<IAttributes>;
