import { IExtendId } from './autoGenerated';

export interface IAttributes {
    executedAt: Date;
    error: string;
}
/**
 * タスク実行結果インターフェース
 */
export type ITaskExecutionResult = IExtendId<IAttributes>;
